// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommentsPlus.Overview
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCommentsPlus17PackageString = "6dda59d8-fd13-4d8b-b715-38674320ce66";
        public static Guid guidCommentsPlus17Package = new Guid(guidCommentsPlus17PackageString);

        public const string guidCommentsPlus17PackageCmdSetString = "dbca8ea7-fbb9-41ce-953b-71db384c7464";
        public static Guid guidCommentsPlus17PackageCmdSet = new Guid(guidCommentsPlus17PackageCmdSetString);

        public const string guidImagesString = "45a79d00-89c0-4bfa-846e-2feeb097e18f";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string CommandSetGuidString = "dfea86e1-99d5-49e5-86e1-6b9068613fa8";
        public static Guid CommandSetGuid = new Guid(CommandSetGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OverviewWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int TopMenuId = 0x1002;
        public const int TopMenuGroupId = 0x1012;
        public const int OverViewWindowCommandId = 0x0100;
    }
}